//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.11 at 03:41:38 PM BRST 
//


package com.buscape.developer;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency" type="{urn:buscape}CurrencyType"/>
 *         &lt;element name="priceMin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceMax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="links" type="{urn:buscape}LinksType"/>
 *         &lt;element name="thumbnail" type="{urn:buscape}ThumbnailType"/>
 *         &lt;element name="rating" type="{urn:buscape}RatingType"/>
 *         &lt;element name="specification" type="{urn:buscape}SpecificationType"/>
 *         &lt;element name="productDetails" type="{urn:buscape}ProductDetailsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fullDescription" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="totalSellers" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="categoryId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType", propOrder = {
    "productName",
    "productShortName",
    "currency",
    "priceMin",
    "priceMax",
    "links",
    "thumbnail",
    "rating",
    "specification",
    "productDetails"
})
public class ProductType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected String productShortName;
    @XmlElement(required = true)
    protected CurrencyType currency;
    @XmlElement(required = true)
    protected String priceMin;
    @XmlElement(required = true)
    protected String priceMax;
    @XmlElement(required = true)
    protected LinksType links;
    @XmlElement(required = true)
    protected ThumbnailType thumbnail;
    @XmlElement(required = true)
    protected RatingType rating;
    @XmlElement(required = true)
    protected SpecificationType specification;
    @XmlElement(required = true)
    protected ProductDetailsType productDetails;
    @XmlAttribute(required = true)
    protected boolean fullDescription;
    @XmlAttribute(required = true)
    protected int totalSellers;
    @XmlAttribute(required = true)
    protected int categoryId;
    @XmlAttribute(required = true)
    protected int id;

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductShortName() {
        return productShortName;
    }

    /**
     * Sets the value of the productShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductShortName(String value) {
        this.productShortName = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     */
    public void setCurrency(CurrencyType value) {
        this.currency = value;
    }

    /**
     * Gets the value of the priceMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceMin() {
        return priceMin;
    }

    /**
     * Sets the value of the priceMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceMin(String value) {
        this.priceMin = value;
    }

    /**
     * Gets the value of the priceMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceMax() {
        return priceMax;
    }

    /**
     * Sets the value of the priceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceMax(String value) {
        this.priceMax = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link LinksType }
     *     
     */
    public LinksType getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinksType }
     *     
     */
    public void setLinks(LinksType value) {
        this.links = value;
    }

    /**
     * Gets the value of the thumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link ThumbnailType }
     *     
     */
    public ThumbnailType getThumbnail() {
        return thumbnail;
    }

    /**
     * Sets the value of the thumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThumbnailType }
     *     
     */
    public void setThumbnail(ThumbnailType value) {
        this.thumbnail = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link RatingType }
     *     
     */
    public RatingType getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingType }
     *     
     */
    public void setRating(RatingType value) {
        this.rating = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificationType }
     *     
     */
    public SpecificationType getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificationType }
     *     
     */
    public void setSpecification(SpecificationType value) {
        this.specification = value;
    }

    /**
     * Gets the value of the productDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDetailsType }
     *     
     */
    public ProductDetailsType getProductDetails() {
        return productDetails;
    }

    /**
     * Sets the value of the productDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDetailsType }
     *     
     */
    public void setProductDetails(ProductDetailsType value) {
        this.productDetails = value;
    }

    /**
     * Gets the value of the fullDescription property.
     * 
     */
    public boolean isFullDescription() {
        return fullDescription;
    }

    /**
     * Sets the value of the fullDescription property.
     * 
     */
    public void setFullDescription(boolean value) {
        this.fullDescription = value;
    }

    /**
     * Gets the value of the totalSellers property.
     * 
     */
    public int getTotalSellers() {
        return totalSellers;
    }

    /**
     * Sets the value of the totalSellers property.
     * 
     */
    public void setTotalSellers(int value) {
        this.totalSellers = value;
    }

    /**
     * Gets the value of the categoryId property.
     * 
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * Sets the value of the categoryId property.
     * 
     */
    public void setCategoryId(int value) {
        this.categoryId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
