//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.11 at 03:41:38 PM BRST 
//


package com.buscape.developer;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userAverageRating" type="{urn:buscape}UserRatingType"/>
 *         &lt;element name="eBitRating" type="{urn:buscape}EBitRatingType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatingType", propOrder = {
    "userAverageRating",
    "eBitRating"
})
public class RatingType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected UserRatingType userAverageRating;
    @XmlElement(required = true)
    protected EBitRatingType eBitRating;

    /**
     * Gets the value of the userAverageRating property.
     * 
     * @return
     *     possible object is
     *     {@link UserRatingType }
     *     
     */
    public UserRatingType getUserAverageRating() {
        return userAverageRating;
    }

    /**
     * Sets the value of the userAverageRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRatingType }
     *     
     */
    public void setUserAverageRating(UserRatingType value) {
        this.userAverageRating = value;
    }

    /**
     * Gets the value of the eBitRating property.
     * 
     * @return
     *     possible object is
     *     {@link EBitRatingType }
     *     
     */
    public EBitRatingType getEBitRating() {
        return eBitRating;
    }

    /**
     * Sets the value of the eBitRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link EBitRatingType }
     *     
     */
    public void setEBitRating(EBitRatingType value) {
        this.eBitRating = value;
    }

}
